source "yandex" "ubuntu16" {
  service_account_key_file = "./files/packer_key.json"
  folder_id = "b1gqd4jqceu8foa3um2m"
  source_image_family = "ubuntu-1604-lts"
  image_name = "reddit-full-${formatdate("MM-DD-YYYY", timestamp())}"
  image_family = "reddit-full"
  image_description = "Otus Course. Second Image Generated by Packer and YCloud"
  ssh_username = "ubuntu"
  use_ipv4_nat = true
  platform_id = "standard-v1"
  zone = "ru-central1-a"
  subnet_id = "e9b2848jpfr5c6mq1qa4"
  instance_cores = 2
  instance_mem_gb = 2
  disk_name = "otus-packer"
  disk_type = "network-hdd"
  disk_size_gb = 14
}

build {
  sources = ["source.yandex.ubuntu16"]

  provisioner "shell" {
    inline = [
      "sleep 200",
      "sudo apt update && sudo apt -y -qq upgrade && sudo apt autoremove -y -qq"
    ]
  }

  provisioner "shell" {
   name = "ruby"
   script = "./scripts/install_ruby.sh"
   execute_command = "sudo {{.Path}}"
 }

  provisioner "shell" {
   name = "mongodb"
   script = "./scripts/install_mongodb.sh"
   execute_command = "sudo {{.Path}}"
 }

  provisioner "shell" {
    name = "reddit"
    script = "./scripts/raise_reddit.sh"
    execute_command = "sudo {{.Path}}"
  }
}
