source "yandex" "ubuntu16" {
  service_account_key_file = "./files/packer_key.json"
  folder_id = "b1gqd4jqceu8foa3um2m"
  source_image_family = "ubuntu-1604-lts"
  image_name = "reddit-base-${formatdate("MM-DD-YYYY", timestamp())}"
  image_family = "reddit-base"
  image_description = "Otus Course. First Image Generated by Packer and YCloud"
  ssh_username = "ubuntu"
  use_ipv4_nat = true
  platform_id = "standard-v1"
  zone = "ru-central1-a"
  subnet_id = "e9b2848jpfr5c6mq1qa4"
}

build {
  sources = ["source.yandex.ubuntu16"]

  provisioner "shell" {
   name = "ruby"
   script = "./scripts/install_ruby.sh"
   execute_command = "sudo {{.Path}}"
 }

  provisioner "shell" {
   name = "mongodb"
   script = "./scripts/install_mongodb.sh"
   execute_command = "sudo {{.Path}}"
 }
}
