#cloud-config
users:
  - name: olexasha
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4V+M1fQp2l+hAUQ2Km4rzLjvelxLp9BvFEER5SgqUjxgwKWD0Peyg8ojLLB5hf9hFU9K+mQYfoj3YpYxjFdGXUk1ii0vPfy4aZtEbsC92dtRTqSjtJY7GO35eBpV9dRX8eBOXBEfExO8gKrPMZybgQ8JL423fBdL5MLaWj1+OnhF79AlLx5Ko7Crc8WwOl0XOjll0w9tIVcizvw5BQynKlUHBu4tHc/DqhbFrj4GxwYecTo2mOY56KiLYeN+vJdfhMmGW8hH2MBQs51UtpN/ZccYxnLq6nMukyju+82E+Kq2hrIjcnkjGHLRy1sWVM1MKyWZBYd6/8gKxxdfs2qtA3U+4GqV8Ztw1hLWddUcAZygJqWm7XVT3pwxRF6jclh4dd/9fD8ahvyRVeMKERA4SEpKvxYr9lV4TR8AC/lUCdUdUCtCHGIqW7/dMfkOR+rSxjEwMCzw0FeGVAOiIORWyv/zVQNIT0Dh1WebWVkTQBF03vF8tfwu4qcLERpBQVlk= appuser
write_files:
  - path: /home/olexasha/scripts/install_ruby.sh
    permissions: 0501
    content: |
      #!/bin/bash
      sudo apt update
      sudo apt install -y ruby-full ruby-bundler build-essential
      if [[ $(ruby -v) == *"ruby 2."* ]]; then
        echo "[debug] Ruby installed succesfully"
      else
        echo "[debug] Something went wrong! Ruby hasnt installed!"
      fi
      if [[ $(bundler -v) == *"Bundler version 1."* ]]; then
        echo "[debug] Bundler installed succesfully"
      else
        echo "[debug] Something went wrong! Bundler hasnt installed!"
      fi
  - path: /home/olexasha/scripts/install_mongodb.sh
    permissions: 0501
    content: |
      #!/bin/bash
      wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      sudo apt update
      sudo apt install -y mongodb-org
      sudo systemctl start mongod
      sudo systemctl enable --now mongod
      STATUS=$(sudo systemctl status mongod)
      if [[ $STATUS == *"active (running)"* ]]; then
        echo "[debug] MongoDB is active and running"
      else
        echo "[debug] Something went wrong! MongoDB is not running"
      fi
      if [[ $STATUS == *"enabled"* ]]; then
        echo "[debug] MongoDB is enabled and will start at boot"
      else
        echo "[debug] Something went wrong! MongoDB is not enabled"
      fi
  - path: /home/olexasha/scripts/deploy.sh
    permissions: 0501
    content: |
      #!/bin/bash
      sudo apt update
      sudo apt install -y git
      # shellcheck disable=SC2164
      mkdir /home/olexasha/git_repos && cd /home/olexasha/git_repos
      git clone -b monolith https://github.com/express42/reddit.git
      cd reddit && bundle install
      puma -d
      # shellcheck disable=SC2009
      PORT=$(ps aux | grep puma | grep -v grep | sed -n 's/.*:\([0-9]\{1,\}\).*/\1/p')
      if [[ -n "$PORT" ]]; then
          echo "[debug] Puma is running on port $PORT"
      else
          echo "[debug] Puma is not running"
      fi
  - path: /home/olexasha/scripts/startup.sh
    permissions: 0501
    content: |
      #!/bin/bash
      /home/olexasha/scripts/install_ruby.sh && /home/olexasha/scripts/install_mongodb.sh && /home/olexasha/scripts/deploy.sh
runcmd:
  - /home/olexasha/scripts/startup.sh
