#cloud-config
users:
  - name: olexasha
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDuTenX2GzAgnTbpB7RVr3uCnCacqUi3P7AKlXVn9STVnusqkSQZ4tTh5VIBEtbgTFGv0PxgP+99Sj+e93tBArBEq3ukQuAIMBFAS3vOZ0+UVs5w87p2mJXhLXfh3nc/DDAW3XsWijx+kyFV665oNvLd3r7Y3+6R2r8LT2DJMQTQEk8HoV0da975XTiGpHDLKFUExsQd/Nc877uOzUVH20+sLrnlwXSwTNKAautPAMehdoPQjKfDHXL3dHzCm6d7iLB35aHas4/yA+pSJAQB9UYGCx8aXHSVML/SUI7HoS/PTFx26K9bay1rlSDFXY0LYtrhb3wPKCFnfXD2dwgMFW+DDtJuyTItACAQGCFFeESCow84GP+mcs4ZT7J+vb1MBH3R0VAibVeXLyATTEZoWhuewZ2x/VoK5r8w8f8YbNSKk/tvNOBu8B8dHIdJShCkXfLKOMFNs4QdeTJxSiWZzEwy5J5WLo7oE58FUQEp9kcO6r01rNm8AfZu7AqAjmkrC0= Дефолтный публичный ключ
write_files:
  - path: /home/olexasha/scripts/install_ruby.sh
    permissions: 0501
    content: |
      #!/bin/bash
      sudo apt update
      sudo apt install -y ruby-full ruby-bundler build-essential
      if [[ $(ruby -v) == *"ruby 2."* ]]; then
        echo "[debug] Ruby installed succesfully"
      else
        echo "[debug] Something went wrong! Ruby hasnt installed!"
      fi
      if [[ $(bundler -v) == *"Bundler version 1."* ]]; then
        echo "[debug] Bundler installed succesfully"
      else
        echo "[debug] Something went wrong! Bundler hasnt installed!"
      fi
  - path: /home/olexasha/scripts/install_mongodb.sh
    permissions: 0501
    content: |
      #!/bin/bash
      wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
      echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      sudo apt update
      sudo apt install -y mongodb-org
      sudo systemctl start mongod
      sudo systemctl enable --now mongod
      STATUS=$(sudo systemctl status mongod)
      if [[ $STATUS == *"active (running)"* ]]; then
        echo "[debug] MongoDB is active and running"
      else
        echo "[debug] Something went wrong! MongoDB is not running"
      fi
      if [[ $STATUS == *"enabled"* ]]; then
        echo "[debug] MongoDB is enabled and will start at boot"
      else
        echo "[debug] Something went wrong! MongoDB is not enabled"
      fi
  - path: /home/olexasha/scripts/deploy.sh
    permissions: 0501
    content: |
      #!/bin/bash
      sudo apt update
      sudo apt install -y git
      # shellcheck disable=SC2164
      mkdir /home/olexasha/git_repos && cd /home/olexasha/git_repos
      git clone -b monolith https://github.com/express42/reddit.git
      cd reddit && bundle install
      puma -d
      # shellcheck disable=SC2009
      PORT=$(ps aux | grep puma | grep -v grep | sed -n 's/.*:\([0-9]\{1,\}\).*/\1/p')
      if [[ -n "$PORT" ]]; then
          echo "[debug] Puma is running on port $PORT"
      else
          echo "[debug] Puma is not running"
      fi
  - path: /home/olexasha/scripts/startup.sh
    permissions: 0501
    content: |
      #!/bin/bash
      /home/olexasha/scripts/install_ruby.sh && /home/olexasha/scripts/install_mongodb.sh && /home/olexasha/scripts/deploy.sh
runcmd:
  - /home/olexasha/scripts/startup.sh
